import type { Template } from '../types/index'
import { CANVAS_WIDTH, SAFE_ZONE_LEFT } from './constants'

export const templates: Template[] = [
  {
    id: 'minimal-gradient',
    name: 'Minimal Gradient',
    description: 'Clean gradient background with simple text',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'Your Name',
        fontFamily: 'Inter, sans-serif',
        fontSize: 64,
        fontWeight: 'bold',
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 40, y: 120 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Professional Title',
        fontFamily: 'Inter, sans-serif',
        fontSize: 28,
        fontWeight: 'normal',
        color: '#e0e7ff',
        position: { x: SAFE_ZONE_LEFT + 40, y: 200 },
        rotation: 0,
        opacity: 0.9,
        visible: true,
      },
    ],
    palette: ['#667eea', '#764ba2', '#ffffff', '#e0e7ff'],
    fonts: ['Inter'],
  },
  {
    id: 'tech-mesh',
    name: 'Tech Mesh',
    description: 'Modern gradient mesh background',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(to right, #4f46e5, #7c3aed, #db2777)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'Full Stack Developer',
        fontFamily: 'Inter, sans-serif',
        fontSize: 56,
        fontWeight: 'bold',
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 50, y: 100 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Building the future, one line at a time',
        fontFamily: 'Inter, sans-serif',
        fontSize: 24,
        fontWeight: 'normal',
        color: '#f3e8ff',
        position: { x: SAFE_ZONE_LEFT + 50, y: 180 },
        rotation: 0,
        opacity: 0.85,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'linkedin',
        label: '/yourprofile',
        style: 'solid',
        gap: 8,
        size: 24,
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 50, y: 280 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#4f46e5', '#7c3aed', '#db2777', '#ffffff'],
    fonts: ['Inter'],
  },
  {
    id: 'corporate',
    name: 'Corporate',
    description: 'Professional corporate style',
    background: {
      type: 'background',
      mode: 'solid',
      value: '#1e293b',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'John Doe',
        fontFamily: 'Arial, sans-serif',
        fontSize: 72,
        fontWeight: 'bold',
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 60, y: 80 },
        rotation: 0,
        opacity: 1,
        visible: true,
        plate: {
          enabled: true,
          padding: 20,
          radius: 8,
          color: '#0ea5e9',
          alpha: 0.2,
        },
      },
      {
        type: 'text',
        text: 'Chief Technology Officer',
        fontFamily: 'Arial, sans-serif',
        fontSize: 32,
        fontWeight: 'normal',
        color: '#94a3b8',
        position: { x: SAFE_ZONE_LEFT + 60, y: 200 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'email',
        label: 'john.doe@company.com',
        style: 'minimal',
        gap: 10,
        size: 20,
        color: '#64748b',
        position: { x: SAFE_ZONE_LEFT + 60, y: 280 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#1e293b', '#0ea5e9', '#ffffff', '#94a3b8', '#64748b'],
    fonts: ['Arial'],
  },
  {
    id: 'dark-mode',
    name: 'Dark Mode',
    description: 'Sleek dark theme with accent colors',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'CREATIVE DIRECTOR',
        fontFamily: 'Helvetica, sans-serif',
        fontSize: 48,
        fontWeight: 'bold',
        color: '#818cf8',
        position: { x: SAFE_ZONE_LEFT + 40, y: 100 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Design • Innovation • Strategy',
        fontFamily: 'Helvetica, sans-serif',
        fontSize: 24,
        fontWeight: 'normal',
        color: '#c7d2fe',
        position: { x: SAFE_ZONE_LEFT + 40, y: 165 },
        rotation: 0,
        opacity: 0.8,
        visible: true,
      },
      {
        type: 'qr',
        url: 'https://linkedin.com/in/yourprofile',
        size: 100,
        foreColor: '#818cf8',
        backColor: '#0f172a',
        quietZone: 2,
        position: { x: CANVAS_WIDTH - 160, y: 250 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#0f172a', '#1e1b4b', '#818cf8', '#c7d2fe'],
    fonts: ['Helvetica'],
  },
  {
    id: 'freelancer-card',
    name: 'Freelancer Card',
    description: 'Showcase your services with style',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(to right, #fbbf24, #f59e0b, #ea580c)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'Freelance Designer',
        fontFamily: 'Inter, sans-serif',
        fontSize: 58,
        fontWeight: 'bold',
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 50, y: 90 },
        rotation: 0,
        opacity: 1,
        visible: true,
        shadow: {
          enabled: true,
          blur: 8,
          offset: { x: 0, y: 4 },
          color: 'rgba(0,0,0,0.3)',
        },
      },
      {
        type: 'text',
        text: 'Logo Design | Branding | UI/UX',
        fontFamily: 'Inter, sans-serif',
        fontSize: 22,
        fontWeight: 'normal',
        color: '#451a03',
        position: { x: SAFE_ZONE_LEFT + 50, y: 165 },
        rotation: 0,
        opacity: 0.9,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'website',
        label: 'www.yourportfolio.com',
        style: 'outline',
        gap: 8,
        size: 22,
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 50, y: 260 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#fbbf24', '#f59e0b', '#ea580c', '#ffffff', '#451a03'],
    fonts: ['Inter'],
  },
  {
    id: 'portfolio-qr',
    name: 'Portfolio QR',
    description: 'Clean layout with prominent QR code',
    background: {
      type: 'background',
      mode: 'solid',
      value: '#f8fafc',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'PORTFOLIO',
        fontFamily: 'Arial, sans-serif',
        fontSize: 52,
        fontWeight: 'bold',
        color: '#0f172a',
        position: { x: SAFE_ZONE_LEFT + 50, y: 100 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Scan to view my work',
        fontFamily: 'Arial, sans-serif',
        fontSize: 24,
        fontWeight: 'normal',
        color: '#64748b',
        position: { x: SAFE_ZONE_LEFT + 50, y: 175 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'qr',
        url: 'https://yourportfolio.com',
        size: 140,
        foreColor: '#0f172a',
        backColor: '#ffffff',
        quietZone: 4,
        position: { x: CANVAS_WIDTH - 200, y: 128 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#f8fafc', '#0f172a', '#64748b', '#ffffff'],
    fonts: ['Arial'],
  },
  {
    id: 'abstract-wave',
    name: 'Abstract Wave',
    description: 'Dynamic wave pattern background',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(45deg, #06b6d4, #3b82f6, #8b5cf6)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'Digital Marketer',
        fontFamily: 'Verdana, sans-serif',
        fontSize: 62,
        fontWeight: 'bold',
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 45, y: 95 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Driving Growth Through Data',
        fontFamily: 'Verdana, sans-serif',
        fontSize: 26,
        fontWeight: 'normal',
        color: '#e0f2fe',
        position: { x: SAFE_ZONE_LEFT + 45, y: 175 },
        rotation: 0,
        opacity: 0.9,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'linkedin',
        label: 'Connect with me',
        style: 'solid',
        gap: 10,
        size: 24,
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 45, y: 270 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#06b6d4', '#3b82f6', '#8b5cf6', '#ffffff', '#e0f2fe'],
    fonts: ['Verdana'],
  },
  {
    id: 'clean-photo',
    name: 'Clean Photo',
    description: 'Minimal text over clean background',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(180deg, #ffffff 0%, #f1f5f9 100%)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'Sarah Johnson',
        fontFamily: 'Georgia, serif',
        fontSize: 68,
        fontWeight: 'bold',
        color: '#1e293b',
        position: { x: SAFE_ZONE_LEFT + 55, y: 90 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Product Manager',
        fontFamily: 'Georgia, serif',
        fontSize: 32,
        fontWeight: 'normal',
        color: '#64748b',
        position: { x: SAFE_ZONE_LEFT + 55, y: 180 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'email',
        label: 'sarah@example.com',
        style: 'minimal',
        gap: 8,
        size: 20,
        color: '#475569',
        position: { x: SAFE_ZONE_LEFT + 55, y: 270 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#ffffff', '#f1f5f9', '#1e293b', '#64748b', '#475569'],
    fonts: ['Georgia'],
  },
  {
    id: 'pastel-shape',
    name: 'Pastel Shape',
    description: 'Soft pastel colors with geometric elements',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(135deg, #fecaca 0%, #fed7aa 50%, #fde68a 100%)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'Content Creator',
        fontFamily: 'Inter, sans-serif',
        fontSize: 58,
        fontWeight: 'bold',
        color: '#7c2d12',
        position: { x: SAFE_ZONE_LEFT + 45, y: 100 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Lifestyle • Travel • Photography',
        fontFamily: 'Inter, sans-serif',
        fontSize: 24,
        fontWeight: 'normal',
        color: '#92400e',
        position: { x: SAFE_ZONE_LEFT + 45, y: 175 },
        rotation: 0,
        opacity: 0.85,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'website',
        label: 'yourwebsite.com',
        style: 'outline',
        gap: 8,
        size: 22,
        color: '#78350f',
        position: { x: SAFE_ZONE_LEFT + 45, y: 265 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#fecaca', '#fed7aa', '#fde68a', '#7c2d12', '#92400e'],
    fonts: ['Inter'],
  },
  {
    id: 'geometric',
    name: 'Geometric',
    description: 'Bold geometric patterns and shapes',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(to bottom right, #059669, #10b981, #34d399)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'UX DESIGNER',
        fontFamily: 'Helvetica, sans-serif',
        fontSize: 56,
        fontWeight: 'bold',
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 50, y: 95 },
        rotation: 0,
        opacity: 1,
        visible: true,
        plate: {
          enabled: true,
          padding: 18,
          radius: 0,
          color: '#064e3b',
          alpha: 0.3,
        },
      },
      {
        type: 'text',
        text: 'Crafting delightful user experiences',
        fontFamily: 'Helvetica, sans-serif',
        fontSize: 22,
        fontWeight: 'normal',
        color: '#d1fae5',
        position: { x: SAFE_ZONE_LEFT + 50, y: 185 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'linkedin',
        label: '/uxdesigner',
        style: 'solid',
        gap: 8,
        size: 24,
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 50, y: 270 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#059669', '#10b981', '#34d399', '#ffffff', '#d1fae5'],
    fonts: ['Helvetica'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Modern striped pattern design',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(90deg, #1e40af 0%, #1e40af 50%, #3b82f6 50%, #3b82f6 100%)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'Business Consultant',
        fontFamily: 'Arial, sans-serif',
        fontSize: 54,
        fontWeight: 'bold',
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 55, y: 105 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Strategy • Growth • Innovation',
        fontFamily: 'Arial, sans-serif',
        fontSize: 26,
        fontWeight: 'normal',
        color: '#dbeafe',
        position: { x: SAFE_ZONE_LEFT + 55, y: 180 },
        rotation: 0,
        opacity: 0.9,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'email',
        label: 'consult@business.com',
        style: 'outline',
        gap: 8,
        size: 20,
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 55, y: 270 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#1e40af', '#3b82f6', '#ffffff', '#dbeafe'],
    fonts: ['Arial'],
  },
  {
    id: 'diagonal-gradient',
    name: 'Diagonal Gradient',
    description: 'Smooth diagonal gradient transition',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(135deg, #be123c 0%, #e11d48 50%, #f43f5e 100%)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'Brand Strategist',
        fontFamily: 'Trebuchet MS, sans-serif',
        fontSize: 60,
        fontWeight: 'bold',
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 48, y: 95 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Elevating Brands to New Heights',
        fontFamily: 'Trebuchet MS, sans-serif',
        fontSize: 24,
        fontWeight: 'normal',
        color: '#ffe4e6',
        position: { x: SAFE_ZONE_LEFT + 48, y: 175 },
        rotation: 0,
        opacity: 0.95,
        visible: true,
      },
      {
        type: 'qr',
        url: 'https://linkedin.com/in/brandstrategy',
        size: 110,
        foreColor: '#ffffff',
        backColor: '#be123c',
        quietZone: 3,
        position: { x: CANVAS_WIDTH - 180, y: 245 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#be123c', '#e11d48', '#f43f5e', '#ffffff', '#ffe4e6'],
    fonts: ['Trebuchet MS'],
  },
  {
    id: 'modern-professional',
    name: 'Modern Professional',
    description: 'Contemporary professional design',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(to right, #0f172a 0%, #1e293b 100%)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'Alex Morgan',
        fontFamily: 'Inter, sans-serif',
        fontSize: 66,
        fontWeight: 'bold',
        color: '#f8fafc',
        position: { x: SAFE_ZONE_LEFT + 50, y: 85 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Senior Software Engineer',
        fontFamily: 'Inter, sans-serif',
        fontSize: 30,
        fontWeight: 'normal',
        color: '#94a3b8',
        position: { x: SAFE_ZONE_LEFT + 50, y: 170 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'github',
        label: '/alexmorgan',
        style: 'minimal',
        gap: 10,
        size: 22,
        color: '#cbd5e1',
        position: { x: SAFE_ZONE_LEFT + 50, y: 260 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'linkedin',
        label: '/alex-morgan',
        style: 'minimal',
        gap: 10,
        size: 22,
        color: '#cbd5e1',
        position: { x: SAFE_ZONE_LEFT + 280, y: 260 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#0f172a', '#1e293b', '#f8fafc', '#94a3b8', '#cbd5e1'],
    fonts: ['Inter'],
  },
  {
    id: 'creative-bold',
    name: 'Creative Bold',
    description: 'Bold and colorful creative design',
    background: {
      type: 'background',
      mode: 'gradient',
      value: 'linear-gradient(45deg, #dc2626, #ea580c, #f59e0b, #10b981)',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'CREATIVE STUDIO',
        fontFamily: 'Impact, sans-serif',
        fontSize: 52,
        fontWeight: 'bold',
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 45, y: 105 },
        rotation: 0,
        opacity: 1,
        visible: true,
        shadow: {
          enabled: true,
          blur: 10,
          offset: { x: 0, y: 5 },
          color: 'rgba(0,0,0,0.4)',
        },
      },
      {
        type: 'text',
        text: 'We bring ideas to life',
        fontFamily: 'Impact, sans-serif',
        fontSize: 28,
        fontWeight: 'normal',
        color: '#fffbeb',
        position: { x: SAFE_ZONE_LEFT + 45, y: 175 },
        rotation: 0,
        opacity: 0.95,
        visible: true,
      },
      {
        type: 'contact',
        platform: 'website',
        label: 'creativestudio.com',
        style: 'solid',
        gap: 10,
        size: 24,
        color: '#ffffff',
        position: { x: SAFE_ZONE_LEFT + 45, y: 265 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#dc2626', '#ea580c', '#f59e0b', '#10b981', '#ffffff'],
    fonts: ['Impact'],
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Ultra-clean minimalist approach',
    background: {
      type: 'background',
      mode: 'solid',
      value: '#ffffff',
      locked: true,
      name: 'Background',
      visible: true,
    },
    layers: [
      {
        type: 'text',
        text: 'MINIMALIST',
        fontFamily: 'Helvetica, sans-serif',
        fontSize: 48,
        fontWeight: 'bold',
        color: '#000000',
        position: { x: SAFE_ZONE_LEFT + 50, y: 120 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'text',
        text: 'Designer',
        fontFamily: 'Helvetica, sans-serif',
        fontSize: 32,
        fontWeight: 'normal',
        color: '#404040',
        position: { x: SAFE_ZONE_LEFT + 50, y: 185 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
      {
        type: 'qr',
        url: 'https://yourportfolio.com',
        size: 100,
        foreColor: '#000000',
        backColor: '#ffffff',
        quietZone: 2,
        position: { x: CANVAS_WIDTH - 160, y: 248 },
        rotation: 0,
        opacity: 1,
        visible: true,
      },
    ],
    palette: ['#ffffff', '#000000', '#404040'],
    fonts: ['Helvetica'],
  },
] as any as Template[]

// Helper to get template by id
export const getTemplateById = (id: string): Template | undefined => {
  return templates.find((t) => t.id === id)
}

// Helper to get random template
export const getRandomTemplate = (): Template => {
  return templates[Math.floor(Math.random() * templates.length)]
}

// Helper to get templates by category (could be expanded)
export const getTemplatesByKeyword = (keyword: string): Template[] => {
  const lowerKeyword = keyword.toLowerCase()
  return templates.filter(
    (t) =>
      t.name.toLowerCase().includes(lowerKeyword) ||
      t.description?.toLowerCase().includes(lowerKeyword)
  )
}
